---
- name: Deploy PrestaShop front
  hosts: frontend_master
  become: yes
  vars_files:
    - ../vars/variables.yaml

  tasks:
    - name: Instalar dependencias necesarias
      apt:
        name:
          - php
          - php-mysql
          - php-xml
          - php-curl
          - php-gd
          - php-mbstring
          - php-zip
          - php-intl
          - php-soap
          - unzip
        state: present
        update_cache: yes

    - name: Crear el directorio de PrestaShop
      file:
        path: /var/www/html/
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Descargar PrestaShop
      get_url:
        url: https://assets.prestashop3.com/dst/edition/corporate/8.2.1/prestashop_edition_classic_version_8.2.1.zip
        dest: /tmp/prestashop.zip
        mode: '0644'

    - name: Verificar que el archivo ZIP existe
      stat:
        path: /tmp/prestashop.zip
      register: prestashop_zip

    - name: Fallar si el archivo ZIP no se descargó correctamente
      fail:
        msg: "El archivo PrestaShop no se descargó correctamente."
      when: not prestashop_zip.stat.exists

    - name: Descomprimir PrestaShop
      unarchive:
        src: /tmp/prestashop.zip
        dest: /var/www/html
        remote_src: yes

    - name: Configurar permisos de PrestaShop
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Insertar configuración personalizada en defines.inc.php de PrestaShop
      blockinfile:
        path: /var/www/html/config/defines.inc.php
        marker: "# {mark} ANSIBLE CUSTOM CONFIG"
        block: |
          define('_PS_SSL_PORT_', 443);
          define('_PS_CACHING_SYSTEM_', 'CacheFs');
      when: ansible_facts['os_family'] == "Ubuntu"

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted