---
- name: Playbook para instalar la pila LAMP en el FrontEnd
  hosts: frontend
  become: yes

  tasks:

    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    - name: Instalar el servidor web Apache
      apt:
        name: apache2
        state: present

    - name: Instalar PHP y los m贸dulos necesarios
      apt: 
        name:
          - php
          - php-mysql
          - libapache2-mod-php
          - php-bcmath
          - php-curl
          - php-gd
          - php-imagick
          - php-intl
          - php-memcached
          - php-mbstring
          - php-dom
          - php-zip
          - php-cli
          - php-xmlrpc
          - php-soap
        state: present

    - name: Modificar el valor max_input_vars de PHP
      replace: 
        path: /etc/php/8.3/apache2/php.ini
        regexp: '^;?max_input_vars\s*=\s*\d+'
        replace: 'max_input_vars = 5000'

    - name: Modificar el valor de max_execution_time de PHP
      replace:
        path: /etc/php/8.3/apache2/php.ini
        regexp: '^;?max_execution_time\s*=\s*\d+'
        replace: 'max_execution_time = 300'

    - name: Modificar el valor de memory_limit de PHP
      replace: 
        path: /etc/php/8.3/apache2/php.ini
        regexp: '^memory_limit\s*=\s*\d+[MG]?'
        replace: 'memory_limit = 512M'

    - name: Modificar el valor de post_max_size de PHP
      replace: 
        path: /etc/php/8.3/apache2/php.ini
        regexp: '^post_max_size\s*=\s*\d+[MG]?'
        replace: 'post_max_size = 64M'

    - name: Modificar el valor de upload_max_filesize de PHP
      replace:
        path: /etc/php/8.3/apache2/php.ini
        regexp: '^upload_max_filesize\s*=\s*\d+[MG]?'
        replace: 'upload_max_filesize = 64M'

    - name: Copiar el archivo de configuraci贸n de Apache
      copy:
        src: ../templates/000-default.conf
        dest: /etc/apache2/sites-available/
        mode: 0755

    - name: Habilitar el m贸dulo rewrite de Apache
      apache2_module:
        name: rewrite
        state: present

    - name: Reiniciar el servidor web Apache
      service:
        name: apache2
        state: restarted

    - name: Insertar configuraci贸n personalizada en defines.inc.php de PrestaShop
      blockinfile:
        path: /var/www/html/config/defines.inc.php
        marker: "# {mark} ANSIBLE CUSTOM CONFIG"
        block: |
          define('_PS_SSL_PORT_', 443);
          define('_PS_CACHING_SYSTEM_', 'CacheFs');
      when: ansible_facts['os_family'] == "Ubuntu"
